### ISSUE TITLE
"Every N measures" blocks interfere with each other

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#165]
Repro:

The "every 2 measures" block never fires at the same time as the "every 4 measures" block.  Surely it should.

![screenshot 2018-11-07 19 50 45](https://user-images.githubusercontent.com/2205926/48120579-a1c14500-e2c6-11e8-9552-17b5ff447f4b.png)

The duck should move every time the moose moves.  It doesn't because its event gets interfered with.

**Comment by breville** [comment]
It appears that this might be by design:

https://github.com/code-dot-org/dance-party/blob/513c981724f5e6f3fab563eb5c507fbc85148423/src/p5.dance.interpreted.js#L67

In which case the priority is how many measures/seconds are specified in the event:

https://github.com/code-dot-org/dance-party/blob/513c981724f5e6f3fab563eb5c507fbc85148423/src/p5.dance.interpreted.js#L136

But that doesn't make sense for a student, does it?

**Comment by epeach** [comment]
The fix I had made for this earlier issue appears to have oversimplified the situation and not accounted for this situation.

**Comment by joshlory** [comment]
Weirdly, I'm not able to repro this in an integration test: https://github.com/code-dot-org/dance-party/compare/every-measure-collision-test

**Comment by ryansloan** [comment]
I realized this was an ambiguous spec on my part. I'll try again, let me know if there are any questions or confusion! 
Here's expected behavior:
* Run every applicable event
* Run them in the following order: 
1) `Every N seconds`
2) `Every N measures`
3) `At N seconds`
4) `At N measures`

Within a group (ie: for the `every 2 measures` and `every 4 measures` example, we should execute them in order based on Y position (as is the blockly standard), starting from the top and moving down.

The last item to be executed can potentially override earlier items. For example, with this code:
<img width="357" alt="screen shot 2018-11-07 at 12 32 38 pm" src="https://user-images.githubusercontent.com/1669271/48159130-415fe280-e289-11e8-8d09-7d4a0d9883d3.png">

The `after 8 measures` block completely tramples over the `every 4 measures` block because it is executed last.

**Comment by joshlory** [comment]
@ryansloan I'm confused by this comment:

> we should execute them in order based on Y position (as is the blockly standard), starting from the top and moving down

Wasn't issue https://github.com/code-dot-org/dance-party/issues/43 about code position affecting event ordering?

**Comment by ryansloan** [comment]
@joshlory good point, sorry, there's still some ambiguity, fixing.

**Comment by joshlory** [comment]
Here's what I'd expect... given:

```
Every 2 measures set the background to "green".
Every 4 measures set the background to "blue".
After 6 measures set the background to "red".
```

I'd expect to see:

```
green, blue, red, blue, green, blue, green, blue, ...
```

The "after N time" always wins.  The "every N time" blocks run in order from highest frequency to lowest frequency.  So an "every 2 measure" event would run before an "every 4 measure" event, letting the rarer event clobber the more frequent event.

One gotcha: if I have:

```
After 1 measure set the background to "orange".
After 1 measure set the background to "purple".
```

Then we need to resolve which of these two conflicting statements run first, and which would run second (clobbering the first value).  But if I said:

```
After 1 measure set the background to "orange".
After 1 measure set the foreground effect to "lights".
```

There would be no conflict, and both would take effect.

**Comment by ryansloan** [comment]
Additional requirement that came up in conversation with @Bjvanminnen 
"When <key>" and "When <peak>" should go into the list after "Every N" and "After N", so that they can override. This is so that these rarer events will feel responsive and reactive moreso than pre-scripted actions.

**Comment by ryansloan** [comment]
Adding @joshlory who will pick this up while Brent is out
