### ISSUE TITLE
Selecting a song while project is running is very broken

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#190]
Repro on Chrome, MacOS on last level

Try selecting a song while project is running. Song won't change but when you hit the Reset button, previous song will keep on playing.

**Comment by ryansloan** [comment]
I think the best thing to do is disable the dropdown while your code is running.

**Comment by breville** [comment]
It makes me a bit nervous that [`.unload`](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/Sounds.js#L271) doesn't stop the sound.  It's hard to imagine a garbage collection can complete properly if the sound is still playing.  We can do a UI fix for this particular issue, but are we confident more generally that `.unload` always leads to a clean garbage collection, even if it's delayed because the sound is still playing at the time?

Not sure who knows, but maybe @cpirich or @islemaster?

**Comment by breville** [comment]
Adding onto that previous concern, I did find a weird repro in which I could get the same song playing twice, which seems partly a result of `.unload` not stopping the sound.  See https://github.com/code-dot-org/dance-party/issues/322
