### ISSUE TITLE
Half of the dance actions goes in the opposite direction than indicated in the "do once" blocks

### ISSUE THREAD

**Issue by poorvasingal** [code-dot-org/dance-party#199]
In half of the dance moves, if you choose the "do once" block and choose the left direction, the move will actually happen to the right (and vice versa). Note that the direction seems to be correct if using the "do forever" blocks.

Incorrect dance moves: Clown, Double Jam, Floss (I think), and Roll.

**Comment by uponthesun** [comment]
Dug into this a little as a learning exercise, and as far as I can tell, this is because of this logic which sets the animation frame to halfway through the animation:

https://github.com/code-dot-org/dance-party/blob/master/src/p5.dance.js#L472-L473

I tried changing the code locally to set the frame number to 0 instead, and it uses the correct direction then.

I imagine just reversing the mirror direction would "fix" this, though that doesn't seem great... hopefully there's a better way?

**Comment by islemaster** [comment]
Testing in the playground with this code
```js
makeNewDanceSprite("CAT", null, {x: 200, y: 200});

var move = 0;
everySeconds(0.5, "measures", function () {
  doMoveEachLR('all', move, 1);
  move = (move + 1) % 25;
});
```

**Comment by islemaster** [comment]
Fix is scheduled for the next deploy.
