### ISSUE TITLE
Restrict Tint Palette

### ISSUE THREAD

**Issue by ryansloan** [code-dot-org/dance-party#240]
restrict the palette to only fully saturated primary and secondary colors

**Comment by ryansloan** [comment]
I think I can do this in levelbuildre

**Comment by ryansloan** [comment]
@Bjvanminnen I talked with Josh and Anthony, we're going to find another owner for this one so you can focus on the other items for Monday's Deploy.

**Comment by Bjvanminnen** [comment]
Makes sense. FYI for the new owner, I suspect the easiest fix will be to do something like this: https://github.com/code-dot-org/code-dot-org/blob/staging-next/apps/src/turtle/blocks.js#L67

**Comment by davidsbailey** [comment]
Update: got this working yesterday following the example above, but it changes the available colors for all blocks, not just "set tint". @Bjvanminnen if you have additional context for how to limit this to certain blocks please let me know!

**Comment by Bjvanminnen** [comment]
Ahh yes, I didn't realize we used that color block elsewhere in Dance.

I don't think there's any good way to have the color block show different options based on it's context. I think options are (a) have two different color blocks (which won't prevent you from dragging the other color block onto tint if it's available) (b) customizing the set tint block to have the color dropdown builtin instead of attached, and have this use a different set of color options (c) restrict the options everywhere, which might be fine. @ryansloan would need to weight in.

I'm not sure how difficult (b) would be.

**Comment by davidsbailey** [comment]
per convo with @ryansloan , it sounds like we want option (b). to maintain backward compatibility, we would keep the old "set tint" block (but remove it from the toolbox), and create a new "set tint" block with the color picker built-in. @nkiruka , from a loc perspective, does it seem possible to do this in a way that would make the new block and old blocks keep using the existing translations?
