### ISSUE TITLE
First time reloads the page regardless of age chosen

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#306]
Previously, I believe we only reloaded the page after choosing an age (on first visit) if you chose an older age.

Now, it reloads the page after any age is chosen.

This is a poor user experience, increases network traffic for schools, and increases load on us.

Ideally we would never reload, but at minimum we should only reload for as few cases as possible, such as older ages in which we are going to load additional songs.

**Comment by joshlory** [comment]
Related bug: https://github.com/code-dot-org/dance-party/issues/126.

**Comment by epeach** [comment]
There's a solid chance this was fixed with the latest deploy: https://github.com/code-dot-org/code-dot-org/pull/25957
Are you still able to repro this?

**Comment by epeach** [comment]
I believe this occurs when this line is triggered: https://github.com/code-dot-org/code-dot-org/blob/42590b13875546bd2d4ddf16be4dd389ec31a6d2/apps/src/templates/AgeDialog.jsx#L85

The latest deploy should mean that this happens very rarely. It happened to me on the first prod load this morning and not since then. Are you still able to repro?

**Comment by breville** [comment]
Looks to be much improved.  Thanks.
