### ISSUE TITLE
Can wreck browser with "every 0.001 measures"

### ISSUE THREAD

**Issue by breville** [code-dot-org/dance-party#321]
It's possible to bring browser performance to its knees pretty easily:

![screenshot 2018-11-13 13 52 01](https://user-images.githubusercontent.com/2205926/48387812-576b1880-e74b-11e8-8c62-18aa051593ef.png)

**Comment by ryansloan** [comment]
The youths do like to find ways to crash code.org. Can we just floor it at some reasonable place? Not sure where the reasonable line is, but from a product perspective we need to support .25 because quarter notes are an interesting unit that we've seen people explore. I am fine drawing the line at .25 unless @mrjoshida has a better recommendation

**Comment by islemaster** [comment]
I did a little initial exploration of this and was going to suggest 0.05 as a minimum value for both measures and seconds.  That's 20 events per second (less than once per frame) and allows sixteenth notes both when given in measures (0.0625 measures) or in seconds at most tempos (0.05 seconds up to 240bpm).

If we're worried that will still crush performance, bumping the minimum to 0.1 (quarter) notes puts us at a maximum of 10 events per second, which is pretty typical for an event loop in a game.

**Comment by ryansloan** [comment]
@islemaster Let's use .1

**Comment by joshlory** [comment]
(We'll want to restrict this in the block, and also validate it at the API layer.)

**Comment by islemaster** [comment]
Fix shipped yesterday!
