### ISSUE TITLE
Age filtering flag conflicts with dialog

### ISSUE THREAD

**Issue by alicesteinglass** [code-dot-org/dance-party#351]
I clicked on the all ages link in the lesson plan. It still asked me my age. I said I was 16. On the second level, I could see all the songs including ed sheeran.

**Comment by ryansloan** [comment]
I repro with the following repro steps:
Signed out, open
Click ""
Click the first bubble
    Observe: Age dialog appears
    Expected: No age dialog
Select an age over 13
   Observe: song list is filtered, as expected due to URL param
Complete the puzzle and click continue
    Observe: Song list on puzzle 2 has all the songs (look for Ed Sheeran)
    Expected: the filter works on the first level and not on subsequent ones.

So requirements are:

- [ ] Age Filter query parameter prevents song selector from appearing
- [ ] Age filter query parameter is stored and applies to subsequent levels in the session

(I'm guessing the second is an issue because the song selector appears and overrides the setting?)
