### ISSUE TITLE
Can't change the starter code on level 3

### ISSUE THREAD

**Issue by joshlory** [code-dot-org/dance-party#394]
Can pass the level no problem, but if a student wants to change "Dab" in the starter code to something else, they can't open the dropdown:

<img src="https://user-images.githubusercontent.com/413693/48519869-59080f80-e823-11e8-8467-798deb4e2d3d.png" width="320">

On https://studio.code.org/s/dance/stage/1/puzzle/3

**Comment by joshlory** [comment]
Also can't copy and paste the read-only block on level 2.  Via @kiki-lee's play-through on YouTube: https://www.youtube.com/watch?v=Er069IDWQ5U&t=188.

**Comment by mrjoshida** [comment]
I wasn't aware that we'd locked any blocks in this progression

**Comment by ryansloan** [comment]
This was changed a while ago, because the success conditions were fragile - it was easy to change the starter code and then get into a state where you couldn't pass for unknown reasons. Students aren't spending much time on this level per GA, and it has high fun-o-meter and low drop-off, I am reluctant to change and potentially get those earlier problems back again.
