### ISSUE TITLE
Level 12 is not translated even though we have translations

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#405]
need to hook up our translations to the instructions in level 12

**Comment by davidsbailey** [comment]
Assigning to Elijah since the only work here is an external sync which he will do. Thanks, Elijah!

**Comment by simplycloud** [comment]
should we re-test this after yesterday's build and sync?

**Comment by davidsbailey** [comment]
After yesterday's sync, I am still not seeing translated instructions when viewing https://studio.code.org/s/dance/stage/1/puzzle/12. When I look at the translations in long_instructions.en.yml or long_instructions.es-ES.yml, I am still seeing `Dance_Party_11.5` rather than `Dance_Party_11_5`.

**Comment by davidsbailey** [comment]
It looks like Elijah is out today. I've got a different fix, which is to manually rename these translations: https://github.com/code-dot-org/code-dot-org/pull/26196

If we are going to ship this solution Monday, we'd probably need to merge it to staging today so that we can verify it is working there. any objections @ryansloan @joshlory @simplycloud?

**Comment by Hamms** [comment]
Ah, I apologize for the confusion; although it is true that a sync was _merged_ on the 20th, that sync was actually _created_ on the 19th, before the original changes were created.

The sync that's being created today (and will hopefully be merged tomorrow) is the sync that should resolve everything. Thanks Dave for taking care of this manually, though!
