### ISSUE TITLE
sharing from mobile seems broken

### ISSUE THREAD

**Issue by simplycloud** [code-dot-org/dance-party#462]
when on an IOS device, the ability to share appears to be broken.

repro:
1. create a dance in level 13.
2. login on mobile device and browse to level 13.
3. click finish to get the sharing screen to display.
4. unable to select link and copy <-- broken?
5. select send to mobile, start typing a phone number and then try to delete a number <-- broken?
6. complete typing a number and select send <-- error message displayed (button shows 'Error' text)

**Comment by davidsbailey** [comment]
Dance puzzle 13 looks even more broken on my Android / Google Pixel (viewport size 684 x 332). the finish button is obscured and unclickable due to the language menu:
![screenshot_20181126-120629](https://user-images.githubusercontent.com/8001765/49043329-92c00b00-f17f-11e8-9f91-692eefbafb26.png)

on iPhone X with iOS version 12 using iOS simulator (viewport size 724 x 375), the Finish button is visible, but the song selector and instructions aren't:
![simulator screen shot - iphone x - 2018-11-26 at 13 33 48](https://user-images.githubusercontent.com/8001765/49043498-22fe5000-f180-11e8-8d32-3ab6b52845e2.png)

So I'm going to assume we only care about this working on 1024x768 and larger.

**Comment by davidsbailey** [comment]
This bug report contains some legit problems, but none of them seem to be specific to mobile:

> 4. unable to select link and copy <-- broken?

Copy appears for me as an option in iOS simulator if I long-press on the share url. @simplycloud , can you confirm that long-press does not solve this for you?

> 5. select send to mobile, start typing a phone number and then try to delete a number <-- broken?

I can repro this on Chrome/Mac -- cannot delete digits from the phone number.

> 6. complete typing a number and select send <-- error message displayed (button shows 'Error' text)

I can repro this on Chrome/Mac -- Error after typing in a number and pressing Send, whether I'm signed in or not.

5 & 6 seem like legit problems so I'll look into fixing those.

**Comment by simplycloud** [comment]
@davidsbailey i will look to see if the long-press works; i believe i tried that though initially. will re-try. thanks!

**Comment by simplycloud** [comment]
@davidsbailey talking to @ryansloan, let's prioritize items 5 and 6 for now and we'll decide if we have time to resolve the others?
