### ISSUE TITLE
There shouldn't be a finish button on puzzle 12

### ISSUE THREAD

**Issue by boatmarina** [code-dot-org/dance-party#481]
Seeing a finish button in prod on puzzle 12 (but not on level-builder).  This also means that the finish dialog comes up when the level completes instead of the continue dialog.

![image](https://user-images.githubusercontent.com/33850843/49100829-a922a100-f229-11e8-82a3-dd2dfda303f9.png)

finish dialog appearing on 12:
![image](https://user-images.githubusercontent.com/33850843/49100860-be97cb00-f229-11e8-8109-5ecd0cbeb2b4.png)

**Comment by boatmarina** [comment]
Might be related to the renaming work?  @davidsbailey

**Comment by davidsbailey** [comment]
It looks like this issue was fixed on levelbuilder 11 days ago, and then never scooped:

<img width="950" alt="screen shot 2018-11-27 at 10 00 40 am" src="https://user-images.githubusercontent.com/8001765/49101557-5813ac80-f22b-11e8-9c6a-7988215ee7a2.png">

@ryansloan , what is the plan for scooping this and any other critical levelbuilder changes? 

I'd be happy to open a PR to fix this if we just need this line, however if there is more levelbuilder content to scoop then it probably makes more sense for this to just be included in that.

**Comment by davidsbailey** [comment]
sounds like the decision is to include this fix partial levelbuilder scoop today.

**Comment by davidsbailey** [comment]
closing in favor of the levelbuilder scoop that should be going out today.
