### ISSUE TITLE
download animation doesn't save correct animation

### ISSUE THREAD

**Issue by bencodeorg** [code-dot-org/dance-party#514]
I get a static image (in a mp4 file, so plays for 5 seconds but nothing changes) of the rainbows background when I download after level 12:
![image](https://user-images.githubusercontent.com/25372625/49174877-274f7800-f2fc-11e8-92f5-f49e77a0046c.png)

This is what my project actually looked like:

![image](https://user-images.githubusercontent.com/25372625/49175025-81503d80-f2fc-11e8-901f-7388d75b9b2d.png)

**Comment by bencodeorg** [comment]
Got it to work once (downloaded correct animation), then, on a third try, got the following:

![image](https://user-images.githubusercontent.com/25372625/49177678-af388080-f302-11e8-91cd-e8925523f083.png)

Not sure what's happening here.

**Comment by ryansloan** [comment]
@bencodeorg could you share your project share URL?

**Comment by bencodeorg** [comment]
https://studio.code.org/projects/dance/3doNl0bRqd5115HClcsz9k_QBAd9LGYA0ip_YgZvQ0Y

**Comment by davidsbailey** [comment]
+1, I ran into this also. from dance puzzle 13, clicking "share" or "finish" and then "Download" gives me the same short rainbow animation. My share link is: https://studio.code.org/projects/dance/Nix-yfgvy8yo039F2zohkg

remixing the project allows video download to work properly, so I suspect this is not something specific to any one dance and has more to do with downloading from a project which is part of a project-backed level, though.

**Comment by davidsbailey** [comment]
a few minutes later, video generation seemed to start working again. then I cleared the level, added some new blocks, and generated a video again. This time, the video appeared to be an older version of the same project. the version I'm now seeing downloaded appears as follows, and does not correspond to any past versions of main.json that still exist in s3:
<img width="404" alt="screen shot 2018-11-29 at 5 47 52 am" src="https://user-images.githubusercontent.com/8001765/49226051-6e8c4600-f39a-11e8-816f-761b6aa96e7e.png">

each time i download the video, the video url looks like: https://dance-api.code.org/videos/video-Nix-yfgvy8yo039F2zohkg.mp4

**Comment by davidsbailey** [comment]
Now I am able to repro the rainbow background issue on a new project, not backing a level: https://studio.code.org/projects/dance/mFO5BGezprN9Db2V7gsMsA

<img width="1181" alt="screen shot 2018-11-29 at 5 54 23 am" src="https://user-images.githubusercontent.com/8001765/49226454-7a2c3c80-f39b-11e8-8fd2-dd4b7b592e6b.png">

**Comment by davidsbailey** [comment]
for this last example, I see the following in my error console:
<img width="458" alt="screen shot 2018-11-29 at 5 59 50 am" src="https://user-images.githubusercontent.com/8001765/49226640-122a2600-f39c-11e8-8937-0d23d3cc8937.png">
the full URL is: https://dance-api.code.org/videos/video-mFO5BGezprN9Db2V7gsMsA.mp4

**Comment by Hamms** [comment]
This should be resolved; I confirmed that this wasn't manifesting on staging, just on production (even though they should be identical) so I kicked off a redeploy and that fixed things.

Although this issues is "fixed" I have a lingering concern on two fronts; first, that no visible errors in X-Ray or CloudWatch were generated because of this, and second that a difference between production and staging came up. I'm also worried that this could be something like a memory leak, that only comes up after a certain amount of time.

I'm leaving this issue open to track further investigation

**Comment by uponthesun** [comment]
Adding more from our investigation:

@Hamms determined that the lambda would be in a good state after each deploy and render videos correctly, but after several minutes of production traffic, would get into a bad state where most or all subsequent requests would result in broken videos. Redeploying to the lambda would fix this temporarily.

We also added logging and inspected the input files and determined that there was no problem with the input files, and that the same input would initially work but then break once the lambda got into a bad state.

Based on these observations, and information about the lambda execution context being potentially reused between invocations ( https://docs.aws.amazon.com/lambda/latest/dg/running-lambda-code.html ), we decided it was likely to be some kind of state shared in the execution context that gets corrupted somehow. The logging we added indicated that the file system in the shared context was ok, so it was likely some mutable object in the top-level scope in the js code. 

We tried moving the canvas object from being initialized at top level to within the function call, and that appears to have fixed the issue, though we still don't know why the canvas object seems to get corrupted eventually when reused.

**Comment by Hamms** [comment]
Upon further investigation, this appears to be caused by https://github.com/Automattic/node-canvas/issues/702

There are a number of places where we end up scaling a canvas down to zero. This includes a bunch of background and foreground effects which are currently disabled in the lambda for this very reason, but also sprites which can be manually set to size zero by users

![image](https://user-images.githubusercontent.com/244100/49319733-26ad1200-f4b3-11e8-9381-5bd16a7f1cac.png)

Because we were formerly using a single canvas element shared between processes, the canvas breaking in this way caused the experience for all users to be affected. With the new change to one canvas per request, this will only be broken for the user who's breaking it.

I'll open a separate PR to track the more in-depth fix to bypass this node-canvas bug entirely

**Comment by davidsbailey** [comment]
Awesome, nice find @Hamms !
